### ISSUE TITLE
Watch hidden directory

### ISSUE THREAD

**Issue by Yamakaky** [mattgreen/watchexec#45]
```
mkdir .a
touch .a/b
watchexec -w .a/b echo 1
touch .a/b
```
It doesn't echo 1. Same thing with `-w .a`.

BTW, why don't you use https://docs.rs/ignore/0.1.8/ignore/gitignore/index.html? He already did the job ^^

**Comment by mattgreen** [comment]
Right now dotted dirs are [ignored unconditionally](https://github.com/mattgreen/watchexec/blob/4fffb534b6dfa5ba2de25848f1e5002498f15c3b/src/cli.rs#L118-L123), mostly because dotted dirs in dev workflows are not relevant.

If you'd like to submit a PR to override this via a `--no-default-ignore` CLI option I'd be happy to merge it.

**Comment by Yamakaky** [comment]
Well, I use `watchexec` a lot outside development, so it's relevant for me ^^

Even for dev, I'm not sure that's what you want to do. If `.gitignore` exists and it doesn't contain `.a`, the dev may want it to be monitored. Hard to say what users want ^^

**Comment by akerl** [comment]
I ran into this today, my GOPATH is `~/.go`, so I spent a handful of minutes trying to sort out why nothing was happening as I modified source files.

I know roughly 0 Rust, but might take a stab at writing in a --no-default-ignore flag; if nothing else, I'm about to build a modded binary that removes the line responsible.

**Comment by mattgreen** [comment]
Sorry about that @akerl!

I think a better approach based on yours and @Yamakaky's experience is to just to maintain a small blacklist of directories that users probably won't want to watch by default. When I wrote watchexec originally I was writing Haskell a lot, and wanted to ignore `.stack-work`. It is obvious that the default pattern for dotted directories is too broad and surprising.

Additionally we could investigate ways to tell if the user is trying to watch an ignored directory and provide a warning.

**Comment by akerl** [comment]
Opened a PR.

My 2cents: most of the stuff-users-usually-want-to-ignore will probably be in their gitignore, so they should get parsed (that covers temporary files and other noise). For other stuff, I suspect the extension-matching solves it.

I know my primary use case so far has been "when I update code, run the build script/tests, or upload to a server, or some such", and so `watchexec -e go make` has been my go-to invocation. In that case, I'm already excluding all dotfiles in the repo itself by actively aiming for all of go.

I'd actually maybe even consider it a good "Anti-Feature" that "watchexec doesn't try to assume what files you want to include/exclude, allowing you to set them via CLI flags and standard VCS files". But at the end of the day, as long as I can override the default ignore list w/ a command line flag, it's your rodeo :D

**Comment by mattgreen** [comment]
Great points all around. I'll look to nuke the default `.*` ignore pattern, as `.gitignore` almost always covers it. Because the `.*` pattern preceded the implementation of `.gitignore` handling, I never thought about how the `.gitignore` file parsing effectively subsumes that pattern.

P.S. saw you are in Arlington, VA! I used to live in Falls Church until my wife and I migrated north. Small world!

**Comment by akerl** [comment]
Hah, yup!

Thank you for the quick feedback. I've rebased the PR to include your commit and added docs to match the new option.

**Comment by Yamakaky** [comment]
Cool!

**Comment by mattgreen** [comment]
This is in 1.8.1, which is up on Cargo now.
